# Generated by Django 5.2.4 on 2025-07-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_like"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
