# Generated by Django 5.2.4 on 2025-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Users that this user is following', related_name='followers', to='post.userprofile'),
        ),
    ]
